### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by renius** [willchapin/RubyTorrent#2]
➜  RubyTorrent git:(master) git submodule init
➜  RubyTorrent git:(master) git submodule update
➜  RubyTorrent git:(master) ruby lib/ruby_torrent.rb ../../marvin/Continuum.S03E01.rus.LostFilm.TV.torrent ~/Downloads/
lib/ruby_torrent.rb:23:in `require_relative': cannot load such file -- /Users/batman/work/tmp/RubyTorrent/lib/ruby_torrent/utils (LoadError)
	from lib/ruby_torrent.rb:23:in `<main>'

**Comment by willchapin** [comment]
Sorry about that, guys. I didn't see your comments until just now. I've added the utils file to the repo. Better late than never!
