### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by KelseyBlodgett** [willchapin/RubyTorrent#4]
Hi, I did not see a license file. Am I able to use this under an Open Source License? 

thanks

**Comment by willchapin** [comment]
oop. sorry just saw this! 
yes you are absolutely able to use this under Open Source License.

**Comment by KelseyBlodgett** [comment]
Thank you! Do you have a preferred license?

**Comment by willchapin** [comment]
Just the standard MIT open source license is fine.
